---
apiVersion: v1
kind: Pod
metadata:
  name: webpage-server
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.15
    ports:
    - containerPort: 80
    volumeMounts:
    - name: webpage
      mountPath: /var/www/html
  volumes:
    - name: webpage
      persistentVolumeClaim:
        claimName: webpage-claim

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nginx

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: webpage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/www/html"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webpage-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
