apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pr-test-role
  namespace: default
rules:
- apiGroups:
  - "" # "" indicates the core API group
  resources:
  - services
  - configmaps
  - pods
  - secrets
  - endpoints
  verbs:
  - get
  - watch
  - list
